# Completes defaults in https://github.com/helix-editor/helix/blob/master/languages.toml
[[language]]
name = "python"
language-servers = ["ty", "ruff"]
auto-format = true                # ":toggle-option autoformat" to disable
# Requires ruff, that can be installed with pipx
formatter = { command = "sh", args = ["-c", """
  ruff check --select I --fix - | ruff format -
  """] }

[[language]]
name = "toml"
# Requires taplo
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "  " }
# Requires shfmt
formatter = { command = "shfmt", args = ["-i", "4"] }
auto-format = true
